module.exports = {
  apps: [{
    name: "api-express-tienda",
    script: "src/index.js",
     env: {
      NODE_ENV: "production",
      PORT: process.env.PORT,
      DB_HOST: process.env.DB_HOST,
      DB_PORT: process.env.DB_PORT,
      DB_NAME: process.env.DB_NAME,
      DB_USER: process.env.DB_USER,
      DB_PASSWORD: process.env.DB_PASSWORD,
    },
     instances: 1,
     exec_mode: "fork",
    error_file: "logs/err.log",
    out_file: "logs/out.log",
    log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    merge_logs: true,
    autorestart: true,
    max_memory_restart: "500M",
    watch: false,
    ignore_watch: ["node_modules", "logs"],
  }],
};
